"""Códigos de violación estables del motor de reglas.

Constantes centralizadas para evitar strings repetidos y números
mágicos dispersos por los módulos de `rules`. Estos valores son parte
del contrato estable de la API (igual que los valores de los enums de
dominio, ver ADR-0005): no se renombran sin una migración explícita.
"""

from __future__ import annotations

EXTINGUISHER_INDIVIDUAL_MUST_BE_HORIZONTAL = "EXTINGUISHER_INDIVIDUAL_MUST_BE_HORIZONTAL"
EXTINGUISHER_AXIS_NOT_PARALLEL_TO_X = "EXTINGUISHER_AXIS_NOT_PARALLEL_TO_X"
EXTINGUISHER_GROUPED_CAPACITY_NONSTANDARD = "EXTINGUISHER_GROUPED_CAPACITY_NONSTANDARD"
ORIENTATION_NOT_ALLOWED = "ORIENTATION_NOT_ALLOWED"
OUT_OF_BOUNDS = "OUT_OF_BOUNDS"
COLLISION = "COLLISION"
UNSUPPORTED = "UNSUPPORTED"
MAX_STACK_EXCEEDED = "MAX_STACK_EXCEEDED"
FRAGILE_SUPPORT = "FRAGILE_SUPPORT"
SUPPORTED_WEIGHT_EXCEEDED = "SUPPORTED_WEIGHT_EXCEEDED"
LOADING_SPACE_WEIGHT_EXCEEDED = "LOADING_SPACE_WEIGHT_EXCEEDED"
UNKNOWN_LOAD_UNIT_REFERENCE = "UNKNOWN_LOAD_UNIT_REFERENCE"
